# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://umanitoba-mathbio.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: '/3MC-PIMS-ICMS-Winnipeg-2025'

# Title of the Site
title: 3MC - PIMS - IDMS - ICMS - Winnipeg 2025
# Description of the Site
description: Summer school on Quantitative molecular and cellular biology - Winnipeg 16-27 June 2025
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /test-mm/assets/images/bg-test-1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: Alison.Skopalek@umanitoba.ca
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  julien-arino
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: 
# URL for the Image of the Author
author-image: assets/images/Gemini_Generated_Image_sg9yxcsg9yxcsg9y.jfif
# 60 Words About the Author
author-about: <p>The 3MC - PIMS - IDMS - ICMS Summer School is co-organised under the umbrellas of 3MC, PIMS and ICMS. It is funded by PIMS and, as an Increasing Diversity in Mathematical Sciences (IDMS) Summer School, through AARMS, CRM, Fields Institute and PIMS.</p> <p>It will be held in on the Fort Garry campus of the University of Manitoba in <a href="https://www.meetingswinnipeg.com/conference/3mc-pims-idms-icms-summer-school">Winnipeg</a>, from 16 to 27 June 2025. Topics of the school are quantitative molecular and cellular biology.</p> <p>The University of Manitoba campuses and research spaces are located on original lands of Anishinaabeg, Ininiwak, Anisininewuk, Dakota Oyate, Dene and Inuit, and on the National Homeland of the Red River Métis.</p> <p>We respect the Treaties that were made on these territories, we acknowledge the harms and mistakes of the past, and we dedicate ourselves to move forward in partnership with Indigenous communities in a spirit of Reconciliation and collaboration. </p>
author-about-short: School on Quantitative molecular and cellular biology, Winnipeg 16-27 June 2025. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Collections
collections:
  people:
    output: true
    permalink: /people/:name/
  projects:
    output: true
    permalink: /projects/:path/



# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
